VN30_SYMBOLS = [
    "ACB",
    "BCM",
    "BID",
    "BVH",
    "CTG",
    "FPT",
    "GAS",
    "GVR",
    "HDB",
    "HPG",
    "MBB",
    "MSN",
    "MWG",
    "PLX",
    "POW",
    "SAB",
    "SSI",
    "STB",
    "TCB",
    "TPB",
    "VCB",
    "VHM",
    "VIB",
    "VIC",
    "VJC",
    "VND",
    "VNM",
    "VPB",
    "VRE",
    "VPI",
]

SYMBOL_ALIASES = {
    "HPG": ["Hoa Phat", "Hòa Phát"],
    "FPT": ["FPT", "FPT Corp", "FPT Corporation"],
    "VNM": ["Vinamilk", "VNM"],
    "VIC": ["Vingroup", "VIC"],
    "VCB": ["Vietcombank", "VCB"],
    "BID": ["BIDV", "BID"],
    "CTG": ["VietinBank", "CTG"],
    "GAS": ["PV Gas", "GAS"],
    "MSN": ["Masan", "MSN"],
    "MWG": ["MWG", "The Gioi Di Dong", "Thế Giới Di Động"],
    "SSI": ["SSI", "SSI Securities"],
    "TCB": ["Techcombank", "TCB"],
    "VPB": ["VPBank", "VPB"],
    "VHM": ["Vinhomes", "VHM"],
    "HDB": ["HDBank", "HDB"],
    "MBB": ["MBBank", "MBB"],
    "PLX": ["Petrolimex", "PLX"],
    "SAB": ["Sabeco", "SAB"],
    "STB": ["Sacombank", "STB"],
    "VRE": ["Vincom Retail", "VRE"],
}
